/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;
import java.util.Scanner;
import java.util.HashMap;
public class Main {
    public static void main(String[] args) {
        Scanner scanner = new Scanner(System.in);
        HashMap<Integer, Integer> sides = new HashMap<>();
        System.out.println("Enter the points of the three sides of the triangle:");
        for (int i = 0; i < 6; i++) {
            sides.put(i, scanner.nextInt());
            System.out.println("Point " + (i + 1) + ": " + sides.get(i));
        }
    }
}
